// ecosystem.config.js
module.exports = {
    apps: [
        {
            name: 'maillayer-nextjs',
            script: 'npm',
            args: process.env.NODE_ENV === 'production' ? 'run start' : 'run dev -- -H 0.0.0.0',
            env: {
                NODE_ENV: process.env.NODE_ENV || 'development',
            },
            // Add log configuration
            log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
            error_file: 'logs/nextjs-error.log',
            out_file: 'logs/nextjs-out.log',
            merge_logs: true,
        },
        {
            name: 'email-worker',
            script: 'workers/email-processor.js',
            env: {
                NODE_ENV: process.env.NODE_ENV || 'development',
                WORKER_DEBUG: process.env.NODE_ENV !== 'production' ? 'true' : 'false',
            },
            // Add better stability and logging for this critical worker
            restart_delay: 3000,
            max_restarts: 10,
            log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
            error_file: 'logs/email-worker-error.log',
            out_file: 'logs/email-worker-out.log',
            merge_logs: true,
            exec_mode: 'fork',
            watch: process.env.NODE_ENV !== 'production' ? ['workers/email-processor.js'] : false, // Only watch in dev mode
            ignore_watch: ['node_modules', 'logs'],
        },
        {
            name: 'cron-checker',
            script: 'workers/cron-checker.js',
            env: {
                NODE_ENV: process.env.NODE_ENV || 'development',
                WORKER_DEBUG: process.env.NODE_ENV !== 'production' ? 'true' : 'false',
            },
            restart_delay: 3000,
            max_restarts: 10,
            log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
            error_file: 'logs/cron-checker-error.log',
            out_file: 'logs/cron-checker-out.log',
            merge_logs: true,
            exec_mode: 'fork',
            watch: process.env.NODE_ENV !== 'production' ? ['workers/cron-checker.js'] : false,
        },
        {
            name: 'campaign-manager',
            script: 'workers/campaign-manager.js',
            env: {
                NODE_ENV: process.env.NODE_ENV || 'development',
                WORKER_DEBUG: process.env.NODE_ENV !== 'production' ? 'true' : 'false',
            },
            restart_delay: 3000,
            max_restarts: 10,
            log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
            error_file: 'logs/campaign-manager-error.log',
            out_file: 'logs/campaign-manager-out.log',
            merge_logs: true,
            exec_mode: 'fork',
            watch: process.env.NODE_ENV !== 'production' ? ['workers/campaign-manager.js'] : false,
        },
        {
            name: 'firebase-sync-worker',
            script: 'workers/firebase-sync-worker.js',
            env: {
                NODE_ENV: process.env.NODE_ENV || 'development',
                WORKER_DEBUG: process.env.NODE_ENV !== 'production' ? 'true' : 'false',
            },
            restart_delay: 3000,
            max_restarts: 10,
            log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
            error_file: 'logs/firebase-sync-worker-error.log',
            out_file: 'logs/firebase-sync-worker-out.log',
            merge_logs: true,
            exec_mode: 'fork',
            watch: process.env.NODE_ENV !== 'production' ? ['workers/firebase-sync-worker.js'] : false,
        },
        {
            name: 'airtable-sync-worker',
            script: 'workers/airtable-sync-worker.js',
            env: {
                NODE_ENV: process.env.NODE_ENV || 'development',
                WORKER_DEBUG: process.env.NODE_ENV !== 'production' ? 'true' : 'false',
            },
            restart_delay: 3000,
            max_restarts: 10,
            log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
            error_file: 'logs/airtable-sync-worker-error.log',
            out_file: 'logs/airtable-sync-worker-out.log',
            merge_logs: true,
            exec_mode: 'fork',
            watch: process.env.NODE_ENV !== 'production' ? ['workers/airtable-sync-worker.js'] : false,
        },
        {
            name: 'google-sheets-sync-worker',
            script: 'workers/google-sheets-sync-worker.js',
            env: {
                NODE_ENV: process.env.NODE_ENV || 'development',
                WORKER_DEBUG: process.env.NODE_ENV !== 'production' ? 'true' : 'false',
            },
            restart_delay: 3000,
            max_restarts: 10,
            log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
            error_file: 'logs/google-sheets-sync-worker-error.log',
            out_file: 'logs/google-sheets-sync-worker-out.log',
            merge_logs: true,
            exec_mode: 'fork',
            watch: process.env.NODE_ENV !== 'production' ? ['workers/google-sheets-sync-worker.js'] : false,
        },
    ],
};
